#' Apply Goodness of Fit Test to the Residuals of a Generalized Linear Model
#'
#' This function can run the goodness of fit test to check if the residuals obtained from a generalized
#' linear model follows a Gamma distribution. Common link functions in glm function can be used here.
#' The function can take a fit object returned by glm functions or you can simply pass design matrix, x, and
#' response vector, y. The function returns Cramer-von Mises statistic along with approximate pvalue for the test.
#'
#' @param x is either a vector of length n or a design matrix with n rows and p columns.
#'
#' @param y is a vector with the same number of observations or number of rows as x.
#'
#' @param l a character vector indicating the link function that should be used for Gamma family. Some common
#' link functions for Gamma family are 'log' and 'inverse'. For more details see \code{\link{make.link}} from stats
#' package in R.
#'
#' @param fit If you have already applied your generalized linear model using a link function for Gamma family,
#' instead of passing your data to the function, you can simply pass your fit object generated by
#' \code{\link{glm}} function. The default value of fit is NULL. If a fit object is provided, x, y, and l will be
#' ignored. The testGLMGamma function then will test if the residuals follow a Gamma distribution.
#' The software will check to make sure the fit object is returned from glm function and link function is indeed
#' from Gamma family. Also make sure to ask glm function to return the design matrix.
#' You can control this by setting x = TRUE in glm function.
#' To read more about this see the help documentation for \code{\link{glm}} function.
#'
#' @param start.value TBD
#'
#' @param control a list of parameters to control the fitting process in glm2 function. For more details, see \code{\link{glm.control}}.
#'
#' @param method a character string to indicate which statistics to calculate.
#' The possible values are 'cvm' for Cramer-von Mises and 'ad' for Anderson-Darling.
#' The default value is 'cvm'.
#'
#' @return A list of two.
#' - Statistic: The Cramer-von-Mises statistic.
#' - pvalue: The approximated pvalue for the GoF test based on EDF.
#'
#' @export
#'
#' @examples
#' set.seed(123)
#' n <- 50
#' p <- 2
#' X <- matrix( rnorm(n*p, mean = 10, sd = 0.1), nrow = n, ncol = p)
#' b <- runif(p)
#' e <- rgamma(n, shape = 3)
#' y <- exp(X %*% b) * e
#' testGLMGamma(x=X,y,l = 'log')
#' myfit <- glm(y~X, family = Gamma('log'), x = TRUE)
#' testGLMGamma(fit = myfit)
testGLMGamma = function(x, y, l, fit = NULL, start.value = NULL, control = NULL, method = 'cvm'){


  if( is.null(control) ){
    control <- glm.control(epsilon = 1e-8, maxit = 100, trace = F)
  }else{
    control <- control
  }

  if( is.null(fit) ){

    family  <- Gamma(link = l)
    n       <- length(y)
    temp    <- applyGLMGamma(x, y, fml = family, sv = start.value, ctl = control, fit.included = NULL)
    Score   <- temp$Score
    pit     <- temp$pit
    par     <- temp$par

    fisher  <- (n-1)*var(Score)/n

    ev      <- getEigenValues(Score, fisher, pit, me = method)
    U2      <- getCvMStatistic(pit)
    pvalue  <- getpvalue(u = U2, eigen = ev)

    res     <- list(Statistic = U2, pvalue = pvalue, converged = temp$converged)
    return(res)

  }else{

    if (!inherits(fit, 'glm')){
      stop('The fit must be \'glm\' object.')
    }

    if( fit$family$family != 'Gamma' ){
      stop('The family in fit must be Gamma.')
    }

    if( is.null(fit$x) ){
      stop('fit object must have the design matrix corresponding to the model. Consider setting x = TRUE in glm function to return x matrix.')
    }

    x       <- fit$x
    y       <- fit$y
    family  <- fit$family
    n       <- length(y)
    temp    <- applyGLMGamma(x, y, fml = family, sv = start.value, ctl = control, fit.included = fit)
    Score   <- temp$Score
    pit     <- temp$pit
    par     <- temp$par

    fisher  <- (n-1)*var(Score)/n

    ev      <- getEigenValues(Score, fisher, pit, me = method)
    U2      <- getCvMStatistic(pit)
    pvalue  <- getpvalue(u = U2, eigen = ev)

    res     <- list(Statistic = U2, pvalue = pvalue, converged = temp$converged)
    return(res)

  }


}
